user_name = "tk011"
weather_api_key = "your_api_key_here"
location = "Tokyo"
country_code = "JP"
[[bookmarks.desktop]]
name = "作業"

[[bookmarks.desktop.items]]
name = "メモ帳"
url = "notepad"

[[bookmarks.web]]
name = "検索"

[[bookmarks.web.items]]
name = "Google"
url = "https://google.com"
