user_name = "tk011"
weather_api_key = "your_api_key_here"
location = "Tokyo"
country_code = "JP"
[[bookmarks.desktop]]
name = "develop"

[[bookmarks.desktop.items]]
name = "notepad"
url = "notepad"

[[bookmarks.web]]
name = "Search"

[[bookmarks.web.items]]
name = "Google"
url = "https://google.com"
